In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Classification/Diabetes_Data.csv"
data = pd.read_csv(url)
data

,Age,Weight,BloodSugar,Gender,Diabetes
0,25,119,130.8,男生,1
1,66,102,128.1,女生,1
2,59,65,103.9,男生,0
3,46,117,94.8,女生,0
4,45,79,57.8,男生,0
...,...,...,...,...,...
395,72,63,97.1,女生,0
396,22,117,156.7,女生,1
397,31,76,119.0,男生,0
398,36,65,96.3,女生,1


In [5]:
data["Gender"] = data["Gender"].map({"男生" : 1, "女生": 0})
data

,Age,Weight,BloodSugar,Gender,Diabetes
0,25,119,130.8,NaN,1
1,66,102,128.1,NaN,1
2,59,65,103.9,NaN,0
3,46,117,94.8,NaN,0
4,45,79,57.8,NaN,0
...,...,...,...,...,...
395,72,63,97.1,NaN,0
396,22,117,156.7,NaN,1
397,31,76,119.0,NaN,0
398,36,65,96.3,NaN,1


In [22]:
from sklearn.model_selection import train_test_split
x = data[["Age", "Weight", "BloodSugar", "Gender"]]
y = data["Diabetes"]

x_train , x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=87)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()
x_train, x_test

(array([[ 47. ,  78. , 112.7,   nan],
        [ 41. ,  79. ,  90.5,   nan],
        [ 28. ,  74. ,  96.4,   nan],
        ...,
        [ 44. ,  53. , 122.2,   nan],
        [ 42. ,  47. ,  69.7,   nan],
        [ 69. , 101. ,  97. ,   nan]]),
 array([[ 74. , 103. , 127.9,   nan],
        [ 73. ,  74. , 106.1,   nan],
        [ 77. ,  65. ,  52. ,   nan],
        [ 22. , 107. , 110. ,   nan],
        [ 31. , 104. ,  98.2,   nan],
        [ 77. ,  47. ,  84.7,   nan],
        [ 50. ,  48. , 103.8,   nan],
        [ 79. ,  87. , 148.4,   nan],
        [ 29. , 106. , 102.8,   nan],
        [ 64. ,  98. , 134. ,   nan],
        [ 27. ,  74. , 115. ,   nan],
        [ 29. ,  81. ,  88.1,   nan],
        [ 45. ,  79. ,  57.8,   nan],
        [ 47. , 106. ,  93.3,   nan],
        [ 60. , 116. , 113.5,   nan],
        [ 63. ,  74. , 102.3,   nan],
        [ 59. ,  65. , 103.9,   nan],
        [ 53. , 107. ,  79. ,   nan],
        [ 52. ,  42. ,  80.5,   nan],
        [ 66. ,  62. ,  72.7,   nan

In [23]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)
x_train

/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1101: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1106: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
/usr/local/lib/python3.12/dist-packages/sklearn/utils/extmath.py:1126: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count


array([[-0.13049114, -0.12021965,  0.35271768,         nan],
       [-0.49202504, -0.07737968, -0.61346817,         nan],
       [-1.27534849, -0.2915795 , -0.35668905,         nan],
       ...,
       [-0.31125809, -1.19121871,  0.76617559,         nan],
       [-0.43176939, -1.44825849, -1.51872338,         nan],
       [ 1.19513315,  0.8650995 , -0.33057592,         nan]])

In [30]:
import numpy as np
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [31]:
w = np.array([1, 2, 3, 4])
b = 1
z = (w*x_train).sum(axis=1) + b
sigmoid(z)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na